[package]
name = "clipboard-shorten"
version = "0.1.0"
authors = ["Ryan McCrystal <rrmccrystal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
urlshortener = "3.0.0"
clipboard = "0.5.0"
url = "2.1.1"